// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyGestWeb.Data;

#nullable disable

namespace MyGestWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MyGestWeb.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MyGestWeb.Models.Cuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SaldoDisponible")
                        .HasColumnType("TEXT");

                    b.Property<string>("TratamientoEspecifico")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Cuentas");
                });

            modelBuilder.Entity("MyGestWeb.Models.DetallePedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoSimpleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioUnitarioHistorico")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PedidoSimpleId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesPedidos");
                });

            modelBuilder.Entity("MyGestWeb.Models.OrdenDistribucion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("OrdenesDistribucion");
                });

            modelBuilder.Entity("MyGestWeb.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Pedido");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("MyGestWeb.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("MyGestWeb.Models.PedidoCompuesto", b =>
                {
                    b.HasBaseType("MyGestWeb.Models.Pedido");

                    b.HasDiscriminator().HasValue("PedidoCompuesto");
                });

            modelBuilder.Entity("MyGestWeb.Models.PedidoSimple", b =>
                {
                    b.HasBaseType("MyGestWeb.Models.Pedido");

                    b.Property<int>("CuentaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrdenDistribucionId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PedidoCompuestoId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("CuentaId");

                    b.HasIndex("OrdenDistribucionId")
                        .IsUnique();

                    b.HasIndex("PedidoCompuestoId");

                    b.HasDiscriminator().HasValue("PedidoSimple");
                });

            modelBuilder.Entity("MyGestWeb.Models.Cuenta", b =>
                {
                    b.HasOne("MyGestWeb.Models.Cliente", "Cliente")
                        .WithMany("Cuentas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MyGestWeb.Models.DetallePedido", b =>
                {
                    b.HasOne("MyGestWeb.Models.PedidoSimple", "PedidoSimple")
                        .WithMany("Detalles")
                        .HasForeignKey("PedidoSimpleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyGestWeb.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PedidoSimple");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("MyGestWeb.Models.PedidoSimple", b =>
                {
                    b.HasOne("MyGestWeb.Models.Cuenta", "CuentaPago")
                        .WithMany("PedidosPagados")
                        .HasForeignKey("CuentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyGestWeb.Models.OrdenDistribucion", "OrdenDistribucion")
                        .WithOne("PedidoAsociado")
                        .HasForeignKey("MyGestWeb.Models.PedidoSimple", "OrdenDistribucionId");

                    b.HasOne("MyGestWeb.Models.PedidoCompuesto", "PedidoCompuestoPertenece")
                        .WithMany("PedidosInternos")
                        .HasForeignKey("PedidoCompuestoId");

                    b.Navigation("CuentaPago");

                    b.Navigation("OrdenDistribucion");

                    b.Navigation("PedidoCompuestoPertenece");
                });

            modelBuilder.Entity("MyGestWeb.Models.Cliente", b =>
                {
                    b.Navigation("Cuentas");
                });

            modelBuilder.Entity("MyGestWeb.Models.Cuenta", b =>
                {
                    b.Navigation("PedidosPagados");
                });

            modelBuilder.Entity("MyGestWeb.Models.OrdenDistribucion", b =>
                {
                    b.Navigation("PedidoAsociado");
                });

            modelBuilder.Entity("MyGestWeb.Models.PedidoCompuesto", b =>
                {
                    b.Navigation("PedidosInternos");
                });

            modelBuilder.Entity("MyGestWeb.Models.PedidoSimple", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
